name: updpkgsums

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master

jobs:
  updpkgsums:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Find updated package
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          # echo "pkgbuild=$(git diff --name-only origin/master origin/${GITHUB_HEAD_REF} "*PKGBUILD" | head -1 | xargs dirname)" >> $GITHUB_ENV
          echo "pkgbuild=PKGBUILD" >> $GITHUB_ENV

      - name: Cache packages and bazel builds
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        if: ${{ env.pkgbuild != '' }}
        with:
          path: .cache
          key: ${{ runner.os }}-${{ env.pkgbuild }}-paru-bazel

      - name: Run update script
        if: ${{ env.pkgbuild != '' }}
        run: |
          /bin/bash .github/renovate-onupdate.sh

      - name: Validate package
        if: ${{ env.pkgbuild != '' }}
        uses: ./.github/actions/aur
        with:
          action: 'updpkgsums'
          pkgname: ${{ env.pkgbuild }}

      - name: Commit
        if: ${{ env.pkgbuild != '' }}
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
