name: Update Package

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master

jobs:
  update_package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Find updated package
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          echo "pkgbuild=$(git diff --name-only origin/master origin/${GITHUB_HEAD_REF} "*PKGBUILD" | head -1 | xargs dirname)" >> $GITHUB_ENV

      - name: Cache packages and bazel builds
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        if: ${{ env.pkgbuild != '' }}
        with:
          path: .cache
          key: ${{ runner.os }}-${{ env.pkgbuild }}-paru-bazel

      - name: Run update script
        if: ${{ env.pkgbuild != '' }}
        run: |
          /bin/bash .github/renovate-onupdate.sh

      - name: Validate package
        if: ${{ env.pkgbuild != '' }}
        uses: ./.github/actions/aur
        with:
          pkgname: ${{ env.pkgbuild }}

      - name: Commit
        if: ${{ env.pkgbuild != '' }}
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
